//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchStat
    {
        public int Id { get; set; }
        public System.Guid CorrelationId { get; set; }
        public string MessageVersion { get; set; }
        public string CompressionType { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Site { get; set; }
        public Nullable<System.DateTime> ValuationDate { get; set; }
        public string Controller { get; set; }
        public string ControllerVersion { get; set; }
    }
}
