//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counterparty
    {
        public long Id { get; set; }
        public string FAName { get; set; }
        public long FAId { get; set; }
        public string SDSName { get; set; }
        public Nullable<long> SDSId { get; set; }
        public Nullable<long> SourceSystemId { get; set; }
        public bool IsInternal { get; set; }
        public bool IsOnboarded { get; set; }
        public bool IsRetail { get; set; }
        public bool NotTrading { get; set; }
        public bool CLS { get; set; }
        public bool DVP { get; set; }
        public Nullable<long> LegalEntitySDSId { get; set; }
    }
}
