//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int Glyph { get; set; }
        public string Type { get; set; }
        public string AdditionalData { get; set; }
        public string Permission { get; set; }
    }
}
