//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskCompressed
    {
        public long Id { get; set; }
        public Nullable<long> TradeId { get; set; }
        public long RiskTypeId { get; set; }
        public string RiskValue { get; set; }
        public long DatasetId { get; set; }
        public string Currency { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string CompressionType { get; set; }
        public Nullable<long> UnderlyingRiskTypeId { get; set; }
        public Nullable<long> CounterpartyId { get; set; }
        public Nullable<long> LegalEntityId { get; set; }
        public Nullable<long> PortfolioId { get; set; }
        public bool HasErrors { get; set; }
    }
}
