//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Children = new HashSet<Schedule>();
            this.ScheduledJobs = new HashSet<ScheduledJob>();
        }
    
        public long ScheduleId { get; set; }
        public Nullable<long> RiskBatchConfigurationId { get; set; }
        public Nullable<long> RequestConfigurationId { get; set; }
        public string TradeSource { get; set; }
        public string ScheduleKey { get; set; }
        public Nullable<long> GroupId { get; set; }
        public Nullable<long> Parent { get; set; }
        public string Site { get; set; }
        public string FundingCurrency { get; set; }
        public string ReportingCurrency { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<long> ExecutableConfigurationId { get; set; }
    
        public virtual RequestConfiguration RequestConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Children { get; set; }
        public virtual Schedule ParentSchedule { get; set; }
        public virtual ScheduleGroup ScheduleGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledJob> ScheduledJobs { get; set; }
        public virtual RiskBatchConfiguration RiskBatchConfiguration { get; set; }
        public virtual ExecutableConfiguration ExecutableConfiguration { get; set; }
    }
}
